(()=>{
const $=q=>document.querySelector(q),$$=q=>[...document.querySelectorAll(q)];
const uid=()=>crypto.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random().toString(16).slice(2)}`;
const tags=s=>(s||'').split(',').map(x=>x.trim()).filter(Boolean),tagText=a=>(a||[]).join(', ');
const esc=s=>String(s||'').replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));
const short=(s,n=120)=>{s=String(s||'').replace(/\s+/g,' ').trim();return s.length>n?s.slice(0,n)+'…':s};
const K=['base','hair','outfit','footwear','accessories','other','negative'];
const L={base:'基本',hair:'髪',outfit:'服',footwear:'足元',accessories:'小物',other:'その他',negative:'ネガティブ'};
const E={status:$('#status'),toast:$('#toast'),log:$('#debugLog'),install:$('#install'),nav:$$('.nav-btn'),tabs:$$('.tab'),libQ:$('#librarySearch'),libC:$('#libraryCount'),lib:$('#libraryList'),itF:$('#itemForm'),itId:$('#itemId'),itMode:$('#itemMode'),itImg:$('#itemImage'),itPrevW:$('#itemPreviewWrap'),itPrev:$('#itemPreview'),itTitle:$('#itemTitle'),itPrompt:$('#itemPrompt'),itTags:$('#itemTags'),itRm:$('#removeItemImage'),itCancel:$('#cancelItemEdit'),chF:$('#charForm'),chId:$('#charId'),chMode:$('#charMode'),chName:$('#charName'),chRaw:$('#charRaw'),chParse:$('#parseCharPrompt'),chClear:$('#clearCharRaw'),chBase:$('#charBase'),chHair:$('#charHair'),chOutfit:$('#charOutfit'),chFoot:$('#charFootwear'),chAcc:$('#charAccessories'),chOther:$('#charOther'),chNeg:$('#charNegative'),chVars:$('#charVariants'),chTags:$('#charTags'),chCancel:$('#cancelCharEdit'),chList:$('#characterList'),scF:$('#sceneForm'),scId:$('#sceneId'),scMode:$('#sceneMode'),scName:$('#sceneName'),scPrompt:$('#scenePrompt'),scTags:$('#sceneTags'),scList:$('#sceneList'),scCancel:$('#cancelSceneEdit'),bChars:$('#builderCharacters'),bScenes:$('#builderScenes'),bExtra:$('#builderExtra'),bSaveScene:$('#saveBuilderScene'),bOut:$('#builderOutput'),bMake:$('#buildPrompt'),bCopy:$('#copyOutput'),bSave:$('#saveOutputOnly'),ex:$('#exportData'),im:$('#importFile'),imp:$('#importData'),wipe:$('#wipeData')};
let db,items=[],chars=[],scenes=[],defer,removeImg=false;
function msg(s){E.toast.textContent=s;E.toast.classList.remove('hide');clearTimeout(msg.t);msg.t=setTimeout(()=>E.toast.classList.add('hide'),1700)}
function log(s,e=''){let line=`[${new Date().toLocaleTimeString('ja-JP',{hour12:false})}] ${s} ${e}`;if(E.log)E.log.textContent=(line+'\n'+E.log.textContent).trim();console.log(s,e)}
function tab(t){E.nav.forEach(b=>b.classList.toggle('on',b.dataset.tab===t));E.tabs.forEach(x=>x.classList.toggle('on',x.id===t))}
function url(b){return b?URL.createObjectURL(b):''}
function blobOf(i){return i.imageBlob||i.img||null}
function dbOpen(){return new Promise((ok,ng)=>{let r=indexedDB.open('imagegen-vault',2);r.onupgradeneeded=()=>{let d=r.result;['items','chars','scenes'].forEach(n=>{if(!d.objectStoreNames.contains(n))d.createObjectStore(n,{keyPath:'id'})})};r.onsuccess=()=>ok(r.result);r.onerror=()=>ng(r.error)})}
function st(n,m='readonly'){return db.transaction(n,m).objectStore(n)}
function all(n){return new Promise((ok,ng)=>{let r=st(n).getAll();r.onsuccess=()=>ok(r.result);r.onerror=()=>ng(r.error)})}
function put(n,v){return new Promise((ok,ng)=>{let r=st(n,'readwrite').put(v);r.onsuccess=()=>ok(v);r.onerror=()=>ng(r.error)})}
function del(n,k){return new Promise((ok,ng)=>{let r=st(n,'readwrite').delete(k);r.onsuccess=ok;r.onerror=()=>ng(r.error)})}
function clr(n){return new Promise((ok,ng)=>{let r=st(n,'readwrite').clear();r.onsuccess=ok;r.onerror=()=>ng(r.error)})}
function splitRaw(raw=''){
  let t=String(raw||'').trim(),o={base:'',hair:'',outfit:'',footwear:'',accessories:'',other:'',negative:''};
  if(!t)return o;
  let labs=[['hair','Hair:'],['outfit','Outfit:'],['footwear','Footwear:'],['footwear','Shoes:'],['accessories','Accessories:'],['negative','Negative prompt:'],['negative','Negative Prompt:'],['other','Other:']],m=[];
  labs.forEach(([k,l])=>{let i=t.indexOf(l);if(i>=0)m.push({k,l,i})});m.sort((a,b)=>a.i-b.i);
  if(!m.length){o.base=t;return o}
  o.base=t.slice(0,m[0].i).trim();
  m.forEach((x,i)=>{let a=x.i+x.l.length,b=i+1<m.length?m[i+1].i:t.length;o[x.k]=t.slice(a,b).trim()});
  return o;
}
function parseVariants(text=''){
  return String(text||'').split('\n').map(x=>x.trim()).filter(Boolean).map(line=>{
    let p=line.split('|').map(x=>x.trim());
    if(p.length>=3)return {group:p[0]||'差し替え',name:p[1]||'無名',prompt:p.slice(2).join(' | ').trim()};
    if(p.length===2)return {group:'差し替え',name:p[0]||'無名',prompt:p[1]||''};
    return {group:'差し替え',name:'無名',prompt:line};
  }).filter(v=>v.prompt);
}
function variantsText(v=[]){return (v||[]).map(x=>`${x.group||'差し替え'} | ${x.name||'無名'} | ${x.prompt||''}`).join('\n')}
function normC(c={}){
  let s=c.sections?{...c.sections}:splitRaw(c.prompt||'');
  return {...c,id:c.id||uid(),name:c.name||'無名キャラ',tags:Array.isArray(c.tags)?c.tags:[],variants:Array.isArray(c.variants)?c.variants:parseVariants(c.variantsText||''),sections:{base:s.base||'',hair:s.hair||'',outfit:s.outfit||'',footwear:s.footwear||'',accessories:s.accessories||'',other:s.other||'',negative:s.negative||c.negative||''}};
}
function charPrompt(c){c=normC(c);let s=c.sections,v=variantsText(c.variants);return [s.base,s.hair&&'Hair: '+s.hair,s.outfit&&'Outfit: '+s.outfit,s.footwear&&'Footwear: '+s.footwear,s.accessories&&'Accessories: '+s.accessories,s.other&&'Other: '+s.other,s.negative&&'Negative prompt: '+s.negative,v&&'Variants:\n'+v].filter(Boolean).join('\n\n')}
function normI(i={}){return {...i,id:i.id||uid(),title:i.title||'無題',prompt:i.prompt||'',tags:Array.isArray(i.tags)?i.tags:[],imageBlob:i.imageBlob||i.img||null,createdAt:i.createdAt||i.at||Date.now(),updatedAt:i.updatedAt||i.at||Date.now()}}
function normS(s={}){return {...s,id:s.id||uid(),name:s.name||'無題シーン',prompt:s.prompt||'',tags:Array.isArray(s.tags)?s.tags:[],createdAt:s.createdAt||Date.now(),updatedAt:s.updatedAt||Date.now()}}
async function load(){items=(await all('items')).map(normI).sort((a,b)=>b.updatedAt-a.updatedAt);chars=(await all('chars')).map(normC).sort((a,b)=>a.name.localeCompare(b.name,'ja'));scenes=(await all('scenes')).map(normS).sort((a,b)=>a.name.localeCompare(b.name,'ja'));drawAll();E.status.textContent=`保存庫 ${items.length} / キャラ ${chars.length} / シーン ${scenes.length}`}
function drawAll(){drawItems();drawChars();drawScenes();drawBuilder()}
function drawItems(){let q=E.libQ.value.toLowerCase(),a=items.filter(i=>[i.title,i.prompt,tagText(i.tags)].join(' ').toLowerCase().includes(q));E.libC.textContent=a.length+'件';E.lib.innerHTML=a.length?a.map(i=>`<article class="card" data-item="${i.id}"><h3>${esc(i.title)}</h3>${blobOf(i)?`<img class="thumb" src="${url(blobOf(i))}">`:''}<p class="muted">${esc(short(i.prompt,160))}</p><p>${i.tags.map(t=>`<span class="tag">${esc(t)}</span>`).join(' ')}</p><div class="actions"><button data-ia="copyP" type="button">プロンプト</button><button data-ia="copyI" type="button">画像</button><button data-ia="edit" type="button">編集</button><button data-ia="del" type="button" class="danger">削除</button></div></article>`).join(''):'<div class="card"><p class="muted">保存データなし。</p></div>'}
function drawChars(){E.chList.innerHTML=chars.length?chars.map(c=>`<details class="fold" data-char="${c.id}"><summary>${esc(c.name)}</summary><p>${c.tags.map(t=>`<span class="tag">${esc(t)}</span>`).join(' ')}</p><span class="section-snippet">${esc(short(c.sections.base,140))}</span><label>登録内容</label><textarea readonly>${charPrompt(c)}</textarea><div class="actions"><button data-ca="copy" type="button">コピー</button><button data-ca="edit" type="button">編集</button><button data-ca="del" type="button" class="danger">削除</button></div></details>`).join(''):'<p class="muted">未登録。</p>'}
function drawScenes(){E.scList.innerHTML=scenes.length?scenes.map(s=>`<details class="fold" data-scene="${s.id}"><summary>${esc(s.name)}</summary><p>${s.tags.map(t=>`<span class="tag">${esc(t)}</span>`).join(' ')}</p><textarea readonly>${s.prompt}</textarea><div class="actions"><button data-sa="copy" type="button">コピー</button><button data-sa="use" type="button">自由入力へ</button><button data-sa="edit" type="button">編集</button><button data-sa="del" type="button" class="danger">削除</button></div></details>`).join(''):'<p class="muted">未登録。</p>'}
function drawBuilder(){
  E.bChars.innerHTML=chars.length?chars.map(c=>{
    let toggles=K.map(k=>`<label class="pill-check"><input type="checkbox" data-role="sec" data-char="${c.id}" data-sec="${k}" ${c.sections[k]?'checked':'disabled'}><span>${L[k]}</span></label>`).join('');
    let vars=(c.variants||[]).map((v,i)=>`<label class="pill-check"><input type="checkbox" data-role="var" data-char="${c.id}" data-var="${i}"><span>${esc(v.group||'差し替え')}：${esc(v.name||'無名')}</span></label>`).join('');
    return `<div class="char-builder"><label class="scene-check"><input type="checkbox" data-role="char" value="${c.id}"><span><b>${esc(c.name)}</b><span class="section-snippet">${esc(short(c.sections.base,110))}</span></span></label><div class="toggle-list">${toggles}</div>${vars?`<p class="muted">差し替えパーツ</p><div class="toggle-list">${vars}</div>`:''}<p class="muted">タグは入れない。</p></div>`
  }).join(''):'<p class="muted">キャラカードを登録する。</p>';
  E.bScenes.innerHTML=scenes.length?scenes.map(s=>`<label class="scene-check"><input type="checkbox" data-role="scene" value="${s.id}"><span><b>${esc(s.name)}</b><span class="section-snippet">${esc(short(s.prompt,140))}</span></span></label>`).join(''):'<p class="muted">保存済みシーンなし。</p>';
}
function fillItem(i){E.itId.value=i.id;E.itMode.textContent='編集中';E.itTitle.value=i.title;E.itPrompt.value=i.prompt;E.itTags.value=tagText(i.tags);E.itImg.value='';removeImg=false;if(blobOf(i)){E.itPrev.src=url(blobOf(i));E.itPrevW.classList.remove('hide')}else{E.itPrevW.classList.add('hide')}E.itCancel.classList.remove('hide');tab('item-editor');scrollTo(0,0)}
function resetItem(){E.itF.reset();E.itId.value='';E.itMode.textContent='新規作成';E.itPrevW.classList.add('hide');E.itCancel.classList.add('hide');removeImg=false}
function fillChar(c){c=normC(c);E.chId.value=c.id;E.chMode.textContent='編集中';E.chName.value=c.name;E.chRaw.value=charPrompt(c);E.chBase.value=c.sections.base;E.chHair.value=c.sections.hair;E.chOutfit.value=c.sections.outfit;if(E.chFoot)E.chFoot.value=c.sections.footwear;E.chAcc.value=c.sections.accessories;E.chOther.value=c.sections.other;E.chNeg.value=c.sections.negative;if(E.chVars)E.chVars.value=variantsText(c.variants);E.chTags.value=tagText(c.tags);E.chCancel.classList.remove('hide');tab('characters');scrollTo(0,0)}
function resetChar(){E.chF.reset();E.chId.value='';E.chMode.textContent='新規作成';E.chCancel.classList.add('hide')}
function fillScene(s){E.scId.value=s.id;E.scMode.textContent='編集中';E.scName.value=s.name;E.scPrompt.value=s.prompt;E.scTags.value=tagText(s.tags);E.scCancel.classList.remove('hide');tab('scenes');scrollTo(0,0)}
function resetScene(){E.scF.reset();E.scId.value='';E.scMode.textContent='新規作成';E.scCancel.classList.add('hide')}
async function copyText(s){try{await navigator.clipboard.writeText(s||'');msg('コピーした')}catch(e){msg('コピー不可')}}
function dl(b,n){let a=document.createElement('a');a.href=url(b);a.download=n;document.body.append(a);a.click();a.remove()}
async function png(b){let im=await createImageBitmap(b),c=document.createElement('canvas');c.width=im.width;c.height=im.height;c.getContext('2d').drawImage(im,0,0);return new Promise(r=>c.toBlob(r,'image/png'))}
async function copyImg(i){let b=blobOf(i);if(!b)return msg('画像なし');try{let p=b.type==='image/png'?b:await png(b);await navigator.clipboard.write([new ClipboardItem({'image/png':p})]);msg('画像コピー')}catch(e){dl(b,'imagegen.png');msg('画像コピー不可。DLした')}}
function secText(c,k){let v=c.sections[k];if(!v)return '';return k==='negative'?'Negative prompt: '+v:v}
function build(){let out=[];$$('[data-role="char"]:checked').forEach(x=>{let c=chars.find(y=>y.id===x.value);if(!c)return;let parts=K.filter(k=>{let t=$(`[data-role="sec"][data-char="${c.id}"][data-sec="${k}"]`);return t&&t.checked&&c.sections[k]}).map(k=>secText(c,k));(c.variants||[]).forEach((v,i)=>{let t=$(`[data-role="var"][data-char="${c.id}"][data-var="${i}"]`);if(t&&t.checked&&v.prompt)parts.push(v.prompt)});if(parts.length)out.push([c.name+':',...parts].join('\n'))});$$('[data-role="scene"]:checked').forEach(x=>{let s=scenes.find(y=>y.id===x.value);if(s&&s.prompt)out.push(s.prompt)});if(E.bExtra.value.trim())out.push(E.bExtra.value.trim());return out.join('\n\n')}
function asData(b){return new Promise(r=>{if(!b)return r(null);let fr=new FileReader;fr.onload=()=>r(fr.result);fr.readAsDataURL(b)})}
function dataBlob(d){return fetch(d).then(r=>r.blob())}
function bind(){
E.nav.forEach(b=>b.onclick=()=>tab(b.dataset.tab));E.libQ.oninput=drawItems;
E.itImg.onchange=()=>{let f=E.itImg.files[0];if(f){removeImg=false;E.itPrev.src=url(f);E.itPrevW.classList.remove('hide')}};E.itRm.onclick=()=>{removeImg=true;E.itImg.value='';E.itPrevW.classList.add('hide');msg('画像を外した')};E.itCancel.onclick=resetItem;
E.itF.onsubmit=async e=>{e.preventDefault();try{let old=items.find(i=>i.id===E.itId.value),file=E.itImg.files[0]||null,b=old?blobOf(old):null;if(removeImg)b=null;if(file)b=file;let v={id:E.itId.value||uid(),title:E.itTitle.value.trim()||'無題',prompt:E.itPrompt.value.trim(),tags:tags(E.itTags.value),imageBlob:b,createdAt:old?.createdAt||Date.now(),updatedAt:Date.now()};await put('items',v);resetItem();await load();tab('library');msg('保存した')}catch(err){log('item save failed',err.message);msg('保存失敗: '+err.message)}};
E.chParse.onclick=()=>{let s=splitRaw(E.chRaw.value);E.chBase.value=s.base;E.chHair.value=s.hair;E.chOutfit.value=s.outfit;if(E.chFoot)E.chFoot.value=s.footwear;E.chAcc.value=s.accessories;E.chOther.value=s.other;E.chNeg.value=s.negative;msg('分解した')};E.chClear.onclick=()=>E.chRaw.value='';E.chCancel.onclick=resetChar;
E.chF.onsubmit=async e=>{e.preventDefault();try{let old=chars.find(c=>c.id===E.chId.value),v=normC({id:E.chId.value||uid(),name:E.chName.value.trim()||'無名キャラ',sections:{base:E.chBase.value.trim(),hair:E.chHair.value.trim(),outfit:E.chOutfit.value.trim(),footwear:E.chFoot?E.chFoot.value.trim():'',accessories:E.chAcc.value.trim(),other:E.chOther.value.trim(),negative:E.chNeg.value.trim()},variants:parseVariants(E.chVars?E.chVars.value:''),tags:tags(E.chTags.value),createdAt:old?.createdAt||Date.now(),updatedAt:Date.now()});await put('chars',v);resetChar();await load();msg('保存した')}catch(err){log('char save failed',err.message);msg('保存失敗: '+err.message)}};
E.scCancel.onclick=resetScene;E.scF.onsubmit=async e=>{e.preventDefault();try{let old=scenes.find(s=>s.id===E.scId.value),v={id:E.scId.value||uid(),name:E.scName.value.trim()||'無題シーン',prompt:E.scPrompt.value.trim(),tags:tags(E.scTags.value),createdAt:old?.createdAt||Date.now(),updatedAt:Date.now()};await put('scenes',v);resetScene();await load();msg('保存した')}catch(err){log('scene save failed',err.message);msg('保存失敗: '+err.message)}};
E.lib.onclick=async e=>{let b=e.target.closest('[data-ia]');if(!b)return;let i=items.find(x=>x.id===b.closest('[data-item]').dataset.item);if(!i)return;let a=b.dataset.ia;if(a==='copyP')copyText(i.prompt);if(a==='copyI')copyImg(i);if(a==='edit')fillItem(i);if(a==='del'&&confirm('削除する？')){await del('items',i.id);await load();msg('削除した')}};
E.chList.onclick=async e=>{let b=e.target.closest('[data-ca]');if(!b)return;let c=chars.find(x=>x.id===b.closest('[data-char]').dataset.char);if(!c)return;let a=b.dataset.ca;if(a==='copy')copyText(charPrompt(c));if(a==='edit')fillChar(c);if(a==='del'&&confirm('削除する？')){await del('chars',c.id);await load();msg('削除した')}};
E.scList.onclick=async e=>{let b=e.target.closest('[data-sa]');if(!b)return;let s=scenes.find(x=>x.id===b.closest('[data-scene]').dataset.scene);if(!s)return;let a=b.dataset.sa;if(a==='copy')copyText(s.prompt);if(a==='use'){E.bExtra.value=s.prompt;tab('builder');msg('自由入力へ入れた')}if(a==='edit')fillScene(s);if(a==='del'&&confirm('削除する？')){await del('scenes',s.id);await load();msg('削除した')}};
E.bMake.onclick=()=>{E.bOut.value=build();msg('組み立てた')};E.bCopy.onclick=()=>copyText(E.bOut.value||build());E.bSave.onclick=async()=>{let p=E.bOut.value||build();if(!p.trim())return msg('空');await put('items',{id:uid(),title:'組み立てプロンプト',prompt:p,tags:['prompt'],imageBlob:null,createdAt:Date.now(),updatedAt:Date.now()});await load();tab('library');msg('保存した')};E.bSaveScene.onclick=()=>{if(!E.bExtra.value.trim())return msg('自由入力が空');E.scId.value='';E.scMode.textContent='新規作成';E.scName.value='共通プロンプト';E.scPrompt.value=E.bExtra.value.trim();E.scTags.value='builder';tab('scenes');msg('シーン保存フォームへ入れた')};
E.ex.onclick=async()=>{let arr=[];for(let i of items)arr.push({...i,imageBlob:null,img:null,imageData:await asData(blobOf(i))});dl(new Blob([JSON.stringify({items:arr,chars,scenes},null,2)],{type:'application/json'}),'imagegen-vault.json');msg('書き出した')};E.imp.onclick=async()=>{try{let f=E.im.files[0];if(!f)return msg('JSONなし');let d=JSON.parse(await f.text());for(let i of d.items||[])await put('items',normI({...i,imageBlob:i.imageData?await dataBlob(i.imageData):i.imageBlob}));for(let c of d.chars||[])await put('chars',normC(c));for(let s of d.scenes||[])await put('scenes',normS(s));await load();msg('読込した')}catch(err){log('import failed',err.message);msg('読込失敗: '+err.message)}};E.wipe.onclick=async()=>{if(!confirm('全削除する？'))return;await clr('items');await clr('chars');await clr('scenes');await load();msg('全削除')};
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();defer=e;E.install.classList.remove('hide')});E.install.onclick=()=>{if(defer){defer.prompt();defer=null;E.install.classList.add('hide')}}}
async function init(){bind();try{E.status.textContent='DB起動中';db=await dbOpen();await load();log('db ready');if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').then(()=>log('service worker registered')).catch(e=>log('sw failed',e.message))}catch(e){E.status.textContent='DB起動失敗';log('init failed',e.message);msg('起動失敗: '+e.message)}}
init();
})();
